CREATE TABLE dbo.es_device_categories (
	id integer NOT NULL,
	n_code integer,
	c_name text,
	b_meter boolean NOT NULL,
	b_tranf boolean NOT NULL,
	b_default boolean NOT NULL,
	b_disabled boolean NOT NULL
);

ALTER TABLE dbo.es_device_categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
	SEQUENCE NAME dbo.es_device_categories_id_seq
	START WITH 1
	INCREMENT BY 1
	NO MAXVALUE
	NO MINVALUE
	CACHE 1
);

ALTER TABLE dbo.es_device_categories OWNER TO mobnius;

COMMENT ON TABLE dbo.es_device_categories IS 'Категории приборов';

COMMENT ON COLUMN dbo.es_device_categories.n_code IS 'Код';

COMMENT ON COLUMN dbo.es_device_categories.c_name IS 'Наименование';

COMMENT ON COLUMN dbo.es_device_categories.b_meter IS 'Признак: Наличие показаний';

COMMENT ON COLUMN dbo.es_device_categories.b_tranf IS 'Признак: Является трансформатором';
